### ISSUE TITLE
md5 > unsafe!

### ISSUE THREAD

**Issue by osworx** [dewawi/dewawi#10]
https://github.com/dewawi/dewawi/blob/038f5af2c51f6aca0a09052303bfb2e37a036f32/application/modules/admin/controllers/UserController.php#L114

Because md5(..) is only unsafe to use, when will this be changed to a better and safe solution with e.g. sha1 & salt?

**Comment by kseones** [comment]
A new version (2.0.0) of the system will be available in a few months with Bcrypt or Argon hashing.

**Comment by osworx** [comment]
@kseones Okay, now we have October 2023 .. you told us you "may" release a new version "in a few months" .. that was May 2021

Any newer (and better) version??
