### ISSUE TITLE
Aktualisierung verwendeter 3PD Komponenten

### ISSUE THREAD

**Issue by osworx** [dewawi/dewawi#11]
Wenn ich mir so die Liste der verwendeten Komponenten ansehe, fürchte ich dass dieses Projekt irgendwie den Anschuß verpasst hat.
Wie sonst kann es ein,d ass dermaßen alte Scripte verwendet werden?
Und auch unsichere, wie z.B. phpMailer.
Oder Zend Framework das es als solches auch nicht mehr gibt.
Oder jQuery das mit der verwendeten Version 1.12.4 auch schon mehr als veraltet ist (und unsicher dazu!).

Wie sehen hier die Pläne für die (sehr) nahe Zukunft aus?
Ansonsten sehe ich da leider keinen (sinnvollen und sicheren) Verwendungszweck für dieses ambitionierte Projekt.

**Comment by kseones** [comment]
Eine komplett neue Version ist bereits in der Entwicklung unter anderem aufgebaut auf Laravel Framework.
