### ISSUE TITLE
Veröffentlichung stabiler Version mit aktuellen Komponenten?

### ISSUE THREAD

**Issue by osworx** [dewawi/dewawi#12]
Die letzte Veröffentlichung einer stabilen Version ist nun bald auch schon 1 Jahr her: 28. Mai 2020
Letzte Commits und rc Versionen lassen einen aber leider nichts gutes sehen, relativ wenige Fortschritte (aktuelle Version von Drittkomponenten, unsichere Passworterstellung, usw.).

Wird dieses Projekt noch gepflegt oder ist es schon am Ende?

**Comment by kseones** [comment]
Sehr bald wird eine neue stabile Version veröffentlicht
