### ISSUE TITLE
Kleine Anregungen

### ISSUE THREAD

**Issue by stmb-100** [dewawi/dewawi#13]
Hallo ich verwende die aktuelle Version von DEWAWI aus dem GIT 1.0.0.RC3
folgende Punkte sind mir aufgefallen.
Gibt es ein Manual zur Konfiguration ?
Ich kann  keine Versionsinformation in meiner Installation finden.
Wie kann ich mein Firmen-Logo auf die PDF-Formulare (Template ?) oben rechts bringen ?
Es wird keine Belegnummer, Rechnungsnummer etc. angezeigt, in der Übersicht nicht, im PDF ist dann nur ein Leeres Feld Belegnummer, Rechnungsnummer etc.
Gibt es eine Einstellung für Kleinunternehmer ohne Umsatzsteuer %19 UStG ?
Die Beispieldaten lassen sich nicht nachträglich in die MySQL Datenbank einspielen.
Ist SSL2 dringend notwendig einer meiner Hoster lässt keine zusätzlichen PHP Extensions zu?

Mfg
Stefan Mühlbauer

**Comment by kseones** [comment]
Hallo, Entschuldigung für meine späte Rückmeldung
Die Versionsinformationen sind in den Einstellungen im Fußtext zu finden
Belegnummern werden nach der Fertigstellung automatisch vergeben (beim Speichern und Buchen)
Kleinunternehmer ohne Umsatzsteuer sowie der Einsatz ohne SSL sind im System leider nicht vorgesehen
Es handelt sich um Open-Source-Software. Beiträge für neue Funktionen und weitere Entwicklung sind herzlich willkommen.
Inzwischen ist eine neue Version verfügbar. Gerne testen und Probleme melden:
https://github.com/dewawi/dewawi/releases/tag/1.1.0
