### ISSUE TITLE
Speichern und buchen

### ISSUE THREAD

**Issue by stmb-100** [dewawi/dewawi#14]
Bei dem Reiter Fertigstellen der Aufträge funktioniert der Klick auf Speichern und buchen nicht. Es verschwindet die PDF Ansicht, es kommt keine Fehlermeldung und auch kein Dialog. Es wurden verschiedene Browser verwendet.
Das Herunterladen des Musterauftrages funktioniert.

**Comment by kseones** [comment]
Vielen Dank für den Hinweis! Der Fehler wurde behoben.
Bitte die neuste Version ([1.0.0](https://github.com/dewawi/dewawi/archive/1.0.0.zip)) herunterladen und frisch neu installieren.
