### ISSUE TITLE
Neue Anfrage

### ISSUE THREAD

**Issue by SP4RT4N3R** [dewawi/dewawi#15]
Diese Fehlermeldung bekomme ich beim starten einer neuen Anfrage
` Trying to access array offset on value of type null in /var/www/html/application/views/helpers/FileManager.php on line 38`

**Comment by kseones** [comment]
Bitte das letzte Abbild herunterladen und erneut testen: https://github.com/dewawi/dewawi/archive/refs/heads/master.zip

**Comment by SP4RT4N3R** [comment]
problem besteht weiter

**Comment by kseones** [comment]
Besteht das Problem nur bei Anfragen oder auch bei anderen Dokumenten?
Gibt es dazu Screenshots?

**Comment by SP4RT4N3R** [comment]
![grafik](https://user-images.githubusercontent.com/95404886/149944065-9e2dd219-1901-47a9-a492-a193514091ab.png)
Besteht zum Beispiel auch bei einem Vorgang, und einer Verkaufsanfrage, einer neuen Rechnung, einer neuen Gutschrift,...
Beim Hinzufügen eines Artikels gibt es die Fehlermeldung nicht

**Comment by kseones** [comment]
Wenn möglich bitte prüfen ob der Fehler mit dem Patch behoben ist
