### ISSUE TITLE
Nach erfolgreicher Installation. 404 error

### ISSUE THREAD

**Issue by deadeyeflint** [dewawi/dewawi#16]
Hallo, 

ich habe dewawi zu Testzwecken auf einem RPi4b+ mit dem OS "dietpi", mariadb, apache2, php 7.4 installieren wollen. Die Installationsroutine funktioniert auch einwandfrei, alle Schritte werden ohne Probleme bearbeitet, jedoch sobald es zur Anmeldung kommen soll (letzter Punkt des Install-scripts), wird der Link auf localhost/dewawi/users/user/login/url/default%7Cindex%7Cindex weitergeleitet. Dieser Link ist aber logischerweise nicht verfügbar auf dem Webserver und auch nach der Installation, ist der Ordner "users" im Webserver nicht vorhanden. 
Installiert ist die aktuelle master-branch vom 03.03.22

Ich finde leider den Fehler nicht. 

Beste Grüße!

**Comment by kseones** [comment]
Hallo, ist mod_rewrite in Apache aktiviert? Zusätzlich muss „AllowOverride All“ in der vHost Konfiguration aktiviert sein, damit die Direktiven in der .htaccess-Datei erlaubt werden.

**Comment by deadeyeflint** [comment]
Lieben Dank. Das hat geklappt. Das Problem saß wieder einmal vor dem Bildschirm! :D
