### ISSUE TITLE
php 8.x compatibility

### ISSUE THREAD

**Issue by osworx** [dewawi/dewawi#19]
Any chance to get a version compatible with php 8.x (explicte 8.2.x) ?
One user already started with a PR: https://github.com/dewawi/dewawi/pull/18
But other issues are to solve.

Seems this project is dead.

**Comment by kseones** [comment]
Please check and report issues https://github.com/dewawi/dewawi/releases/tag/1.1.0

**Comment by tremer-m** [comment]
Hi, I did install the 1.1.0 version and I receive the following error: 

Fatal error: Uncaught Zend_Currency_Exception: No region found within the locale '' in /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php:559 Stack trace: #0 /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php(100): Zend_Currency->setLocale('') #1 /home/webpages/lima-city/destillerie/wawi/application/Bootstrap.php(92): Zend_Currency->__construct(Array) #2 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(673): Bootstrap->_initLocale() #3 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(626): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('locale') #4 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(590): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('locale') #5 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application.php(389): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL) #6 /home/webpages/lima-city/destillerie/wawi/index.php(56): Zend_Application->bootstrap() #7 {main} thrown in /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php on line 559
