### ISSUE TITLE
Login Page not found

### ISSUE THREAD

**Issue by xaptionfw** [dewawi/dewawi#4]
I installed dewawi locally on a macbook in a folder dewawi-0.9. I'm using a mysql database. Configuration succeeded.
When opening http://fw.local/dewawi-0.9 it forwards to
http://fw.local/dewawi-0.9/users/user/login/url/default%7Cindex%7Cindex 
and returns a 404 - not found.

What's wrong?

**Comment by kseones** [comment]
Please download the latest branch here and test it again: https://github.com/dewawi/dewawi/archive/master.zip
Let me know if have any other problems.
