### ISSUE TITLE
Fehler 500 nach Installation

### ISSUE THREAD

**Issue by Walsonde** [dewawi/dewawi#6]
Hallo!

Nachdem ich die Dateien auf meinen Webspace geladen hab und die Installation problemlos lief kann ich nun das Frontend nicht aufrufen, statt dessen kommt ein Fehler 500. Im Error Log des Webhosters steht folgende Fehlermeldung:

`[Wed Dec 09 20:38:13 2020] [error] [pid 2802] core.c(3879): [client
2a02:8071::] AH00124:
 Request exceeded the limit of 10 internal redirects due to probable
configuration error$`

Ich hänge also in einer redirect loop fest. Rufe ich die Seite mit curl auf, steht da Folgendes (natürlich mit anderer URL):

`$ curl https://meine.web.seite -v
  [...]
  < set-cookie: PHPSESSID=1bpcdchd3kn23p9urg5t66vr99; path=/
  < location: /users/user/login/url/default%7Cindex%7Cindex
  [...]`

Der Pfad, welcher unter location steht, den gibt es nicht und da bei der Installation dies in die .htaccess geschrieben wurde:

`  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule /?([A-Za-z0-9_-]+)/?$ index.php?id=$1 [QSA,L]
`

hängt die Seite in einer Schleife fest.

Wie geht's jetzt weiter? Was kann ich tun?

**Comment by kseones** [comment]
Hallo, Installationsscript verändert die .htaccess-Datei nicht, keine Ahnung wo die Zeile her kommt. Am besten alles löschen und frisch neu installieren. Bitte beachten dass mod_rewrite und AllowOverride All in der vHost Konfiguration aktiviert sind.
