### ISSUE TITLE
Fehlermeldung im Backend nach Neuinstallation

### ISSUE THREAD

**Issue by Walsonde** [dewawi/dewawi#7]
Huhu!

Ich habe Dewawi frisch installiert. Während des Installationsprozesses wurden keine Fehler oder Mängel angezeigt. Nach der Installation kann ich die Loginseite problemlos aufrufen aber sobald ich eingeloggt bin, kommt folgende Fehlermeldung und ich kann mich noch nicht einmal mehr ausloggen:

An error occurred
Application error
Exception information:

Message: Could not find row 1
Stack trace:

#0 /usr/www/users/kaikla/magazeno/application/plugins/Acl.php(34): Application_Model_DbTable_Permission->getPermissions()
#1 /usr/www/users/kaikla/magazeno/library/Zend/Controller/Plugin/Broker.php(260): Application_Plugin_Acl->routeShutdown(Object(Zend_Controller_Request_Http))
#2 /usr/www/users/kaikla/magazeno/library/Zend/Controller/Front.php(923): Zend_Controller_Plugin_Broker->routeShutdown(Object(Zend_Controller_Request_Http))
#3 /usr/www/users/kaikla/magazeno/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#4 /usr/www/users/kaikla/magazeno/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#5 /usr/www/users/kaikla/magazeno/index.php(57): Zend_Application->run()
#6 {main}  

Request Parameters:

array (
  'controller' => 'index',
  'action' => 'index',
  'module' => 'default',
)

**Comment by kseones** [comment]
Dieser Fehler ist von Version 0.9 bekannt und wurde schon lange behoben. Bitte hier herunterladen und installieren: https://github.com/dewawi/dewawi/archive/master.zip

**Comment by Walsonde** [comment]
Ich hatte 1.0.0-RC1, das hätte ich Dummbatz dazusagen sollen. Sorry. Jetzt läuft auf den ersten Blick alles. Lieben Dank! <3
