### ISSUE TITLE
Benutzerverwaltung

### ISSUE THREAD

**Issue by Smith-fms** [dewawi/dewawi#8]
Hallo,

die Anlage neuer User mit einem durch den User selbst zu generierenden MD5 ist nicht mehr zeitgemäß und lies mich fast wieder alles löschen. 
Hier sollte dringen etwas geändert werden.

**Comment by kseones** [comment]
Vielen Dank für den Hinweis! Der Fehler wurde behoben, bitte siehe 94c714ab76376b08fb913f4f2f267c5ba0af84d1.

**Comment by osworx** [comment]
Ich sehe hier aber keine Änderung, es wird nach wie vor md5() verwendet!
