### ISSUE TITLE
Fehler bei Anlage neuer Vorgänge

### ISSUE THREAD

**Issue by Smith-fms** [dewawi/dewawi#9]
Bei der Anlage neuer Vorgänge erscheint folgender Fehler:

`Notice: Trying to access array offset on value of type null in /var/www/dewawi/application/views/helpers/FileManager.php on line 38`

**Comment by kseones** [comment]
Dieser Fehler wurde bereits im Januar behoben, am besten bitte die Version RC3 herunterladen.
